#pragma once

#include "common.h"
#include "shader.h"
#include "texture.h"
#include "chunk.h"
#include "chunk_gen.h"
#include "chunk_mesh_gen.h"
#include "meh_hash.h"
#include "player.h"

#include <SDL3/SDL.h>

#define MAX_QUEUED_CHUNKS 64
#define MAX_QUEUED_MESHES 32

inline uint64_t func_hash_chunk_key(const vec2i &key);
inline bool     func_compare_chunk_key(const vec2i &key_a, const vec2i &key_b);
typedef meh::Table<vec2i, Chunk *, func_hash_chunk_key, func_compare_chunk_key, 85> ChunkHashTable;

struct GameWorldInfo {
    uint32_t world_gen_seed;
    int32_t chunks_loaded;
    int32_t chunks_allocated;
    int32_t chunks_queued;
    int32_t meshes_queued;
    int32_t meshes_queued_high_prio;
};

/* Struct of static size for queueing ChunkMeshGenData & ChunkGenData */
template <typename Type, size_t SIZE>
struct StaticGenQueue {
    Type    elements[SIZE];
    Type   *elements_free[SIZE];
    int32_t elements_free_count;

    StaticGenQueue(void) {
        this->clear();
    }

    void clear(void) {
        for(int32_t index = 0; index < SIZE; ++index) { elements_free[index] = &elements[index]; }
        elements_free_count = SIZE;
        in_queue = { };
        finished = { };
    }

    inline bool is_full(void) {
        return elements_free_count == 0;
    }

    Type *get_free_element(void) {
        if(elements_free_count == 0) {
            return NULL;
        }

        Type *free = elements_free[--elements_free_count];
        return free;
    }

    void release_element(Type *element) {
        ASSERT(elements_free_count < SIZE);
        elements_free[elements_free_count++] = element;
    }

    struct Queue {
        Type *queue[SIZE];
        int32_t front;
        int32_t back;
        int32_t size;

        inline bool is_full(void) {
            return size == SIZE;
        }

        inline bool is_empty(void) {
            return size == 0;
        }

        inline bool push(Type *value) {
            if(this->is_full()) {
                return false;
            }

            queue[front] = value;
            front = (front + 1) % SIZE;
            size += 1;
            return true;
        }

        inline bool pop(Type **out_value_ptr) {
            if(this->is_empty()) {
                return false;
            }

            Type *value = queue[back];
            back = (back + 1) % SIZE;
            size -= 1;
            *out_value_ptr = value;
            return true;
        }
    };

    Queue in_queue;
    Queue finished;
};

class World {
public:
    CLASS_COPY_DISABLE(World);
    
    friend class Game;

    explicit World(Game *game);
    ~World(void);

    /* Get _Game_ containing that world */
    Game *get_game(void);

    /* */
    Player &get_player(void);

    /* Delete current world and initialize new one */
    void initialize_new_world(uint32_t seed);

    /* Delete chunks and queues */
    void delete_chunks(void);

    /* Delete the chunk */
    void delete_chunk(vec2i chunk_coords);

    /* Return chunk if has been generated */
    Chunk *get_chunk(vec2i chunk_xz);

    /* Create chunk if doesn't exist, and return it */
    Chunk *get_chunk_create(vec2i chunk_xz, BlockType blocks[CHUNK_SIZE_X * CHUNK_SIZE_Y * CHUNK_SIZE_Z] = NULL);

    /* Return Block and _opt_ Chunk from absolute position, On fail return BlockType::_INVALID */
    BlockType get_block(vec3i block_abs, Chunk **out_chunk = NULL);

    /* Queue chunk to be created */
    void queue_create_chunk(vec2i chunk_xz);

    /* Queue chunk meshes to be build */
    void queue_build_mesh(vec2i chunk_coords, bool high_prio = false);

    /* Build mesh for chunk on main thread */
    void rebuild_mesh_slow(vec2i chunk_coords);

    /* Will be considered for mesh rebuild */
    void set_chunk_should_rebuild_mesh(vec2i chunk_coords, bool important = false);

    /* Check if chunk's neighbours are generated */
    bool chunk_neighbours_generated(vec2i chunk_xz);

    /* Get current world state info */
    GameWorldInfo get_world_info(void);

    /* Iterates through only valid chunks */
    bool iterate_chunks(ChunkHashTable::Iterator &iter);

    /* Insert stuff generated by different threads */
    void insert_generated_chunks(void);
    void insert_generated_meshes(void);

    /* Procedures that generate chunks/meshes from the queue */
    bool generate_next_chunk(void);
    bool generate_next_mesh(void);

    bool can_queue_chunk(void) {
        return !m_chunk_gen_queue.is_full();
    }

    bool can_queue_mesh(void) {
        return !m_mesh_gen_queue.is_full();
    }

    bool can_queue_mesh_high_prio(void) {
        return !m_mesh_gen_queue_high_prio.is_full();
    }


private:
    Game          *m_owner;
    Player         m_player;
    ChunkHashTable m_chunk_table;
    WorldGenSeed   m_gen_seed;

    SDL_Mutex *m_lock_chunk_gen;
    SDL_Mutex *m_lock_mesh_gen;

    StaticGenQueue<ChunkGenData, MAX_QUEUED_CHUNKS> m_chunk_gen_queue;
    StaticGenQueue<ChunkMeshGenData, MAX_QUEUED_MESHES> m_mesh_gen_queue;
    StaticGenQueue<ChunkMeshGenData, MAX_QUEUED_MESHES> m_mesh_gen_queue_high_prio;
};

inline uint64_t func_hash_chunk_key(const vec2i &key) {
    vec2i x = key;
    x.x += 0;
    x.y += 0;
    x.x *= 11;
    x.y *= 31;
    uint64_t hash = (*(uint64_t *)&x.x) | ((*(uint64_t *)&x.y) << 32);
    return hash;
}

inline bool func_compare_chunk_key(const vec2i &key_a, const vec2i &key_b) {
    bool equal = key_a.x == key_b.x && key_a.y == key_b.y;
    return equal;
}
